# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: M


# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: 'atul_anurag'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Atul Anurag"

# Site footer
footer:
  copyright:
    notice: 'Â© {year} admin. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
